/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumul.hello.world;

import java.io.IOException;
import java.util.Map;
import fi.iki.elonen.NanoHTTPD;
import io.github.cdimascio.dotenv.Dotenv;
import io.cumul.sdk.Cumulio;
import org.json.JSONObject;
import com.google.common.collect.ImmutableMap;

public class App extends NanoHTTPD {

    static private Dotenv dotenv;
    
    public App() throws IOException {
        super(4001);
        start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);
        System.out.println("\nRunning! Point your browsers to http://localhost:4001/ \n");
    }

    public static void main(String[] args) {
        try {
            dotenv = Dotenv
                .configure()
                .directory("../")
                .systemProperties()
                .load();
            System.out.println(dotenv.get("CUMUL_KEY"));
            new App();
        } catch (IOException ioe) {
            System.err.println("Couldn't start server:\n" + ioe);
        }
    }

    @Override
    public Response serve(IHTTPSession session) {
        try {
            // Setup connection
            Cumulio client = new Cumulio(dotenv.get("CUMUL_KEY"), dotenv.get("CUMUL_TOKEN"), dotenv.get("API_URL"));

            // On page requests of pages containing embedded dashboards, request an "authorization"
            JSONObject authorization = client.create("authorization", ImmutableMap.builder()
                .put("type", "sso")
                .put("expiry", "24 hours")
                .put("inactivity_interval", "10 minutes")
                .put("username", dotenv.get("USER_USERNAME"))
                .put("name", dotenv.get("USER_NAME"))
                .put("email", dotenv.get("USER_EMAIL"))
                .put("suborganization", dotenv.get("USER_SUBORGANIZATION"))
                .put("integration_id", dotenv.get("INTEGRATION_ID"))
                .put("role", "viewer")
                .build()
            );
            JSONObject authResponse = new JSONObject();
            authResponse.put("status", "success");
            authResponse.put("key", authorization.getString("id"));
            authResponse.put("token", authorization.getString("token"));

            Response response = newFixedLengthResponse(
                authResponse.toString()
            );
            response.addHeader("Content-Type", "application/json");
            return response;
        } catch(Exception e) {
            JSONObject authResponse = new JSONObject();
            authResponse.put("status", "failed");
            Response resp = newFixedLengthResponse(authResponse.toString());
            resp.addHeader("Content-Type", "application/json");
            return resp;
        }

    }
}
